export const API_BASE_URL = "http://localhost:3001/api/v1";

export const API_ENDPOINTS = {
  HEALTH: "/health",
  USERS: "/users",
  LOGIN: "/users/login",
  LOGOUT: "/users/logout",
  PROFILE: "/users/profile",
  REGISTER: "/users/register",
  DELETE_ACCOUNT: "/users/delete",
  CHANGE_PASSWORD: "/users/change-password",
  REQUEST_PASSWORD_RESET: "/users/request-password-reset",
  RESET_PASSWORD_WITH_CODE: "/users/reset-password-with-code",
  STUDY_METHODS: "/metodos-estudio",
  BENEFITS: "/beneficios",
  EVENTS: "/eventos",
  REPORTS: "/reports",
  ACTIVE_METHODS: "/reports/active-methods",
  METHOD_PROGRESS: "/reports/methods",
  SESSION_PROGRESS: "/reports/sessions",
  NOTIFICATIONS_PREFERENCES: "/notificaciones/preferencias",
  NOTIFICATIONS_SCHEDULED: "/notificaciones/programadas",
  MUSIC_ALBUMS: "/musica",
  MUSIC_LIBRARY: "/musica",
  SESSIONS: "/sesiones",
  USER_SESSIONS: "/sesiones",
  INTERESES: "/intereses",
  DISTRACCIONES: "/distracciones",
} as const;